/**
 * Self-host the fonts.
 *
 * The pages loaded Poppins and Inter from fonts.googleapis.com. Two problems
 * with that, and only one of them is cosmetic.
 *
 * The Content-Security-Policy the server sends is style-src 'self' and
 * font-src 'self', so the stylesheet was blocked and the pages fell back to
 * system fonts — silently, with only a console error to say so.
 *
 * The other is that every page load told Google the visitor's IP address, the
 * page they were on and their user agent. For a system holding Kenyan
 * children's records that is a transfer of personal data to a third party
 * outside Kenya, on every screen, for a typeface.
 *
 *   node tools/fetch-fonts.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT  = path.join(ROOT, 'assets', 'fonts');
const CSS  = path.join(ROOT, 'assets', 'css', 'fonts.css');

const URL_ = 'https://fonts.googleapis.com/css2' +
  '?family=Poppins:wght@400;500;600;700&family=Inter:wght@400;500;600&display=swap';

// Ask as a modern browser, or Google serves the older formats.
const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) ' +
           'Chrome/124.0 Safari/537.36';

fs.mkdirSync(OUT, { recursive: true });

const css = await (await fetch(URL_, { headers: { 'User-Agent': UA } })).text();

const seen = new Map();
let localCss = css;

// Latin only. A Kenyan school writes English and Kiswahili; the Cyrillic and
// Greek subsets are 200 KB in the repository that no browser will ever ask for.
const SUBSETS = /^(latin|latin-ext)$/;

for (const m of css.matchAll(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/g)) {
  const url = m[1];
  if (seen.has(url)) continue;
  // A name that says what it is, rather than Google's hash.
  const before = css.slice(0, m.index);
  const family = (before.match(/font-family:\s*'([^']+)'/g) || []).pop()?.match(/'([^']+)'/)[1] || 'font';
  const weight = (before.match(/font-weight:\s*(\d+)/g) || []).pop()?.match(/(\d+)/)[1] || '400';
  const subset = (before.match(/\/\* ([a-z-]+) \*\//g) || []).pop()?.replace(/\/\*|\*\/|\s/g, '') || 'latin';
  const ext = path.extname(new URL(url).pathname) || '.woff2';
  const name = `${family.toLowerCase().replace(/\s+/g, '-')}-${weight}-${subset}${ext}`;

  if (!SUBSETS.test(subset)) { localCss = localCss.replace(new RegExp(
        '@font-face\\s*\\{[^}]*' + url.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '[^}]*\\}', 'g'), ''); continue; }
  const bytes = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer());
  fs.writeFileSync(path.join(OUT, name), bytes);
  seen.set(url, name);
  localCss = localCss.split(url).join(`../fonts/${name}`);
}

const header = `/* Poppins and Inter, served from this origin.
 *
 * Generated by tools/fetch-fonts.mjs. Do not edit by hand — re-run it.
 *
 * These used to come from fonts.googleapis.com, which meant two things: the
 * Content-Security-Policy blocked them, so the pages quietly fell back to
 * system fonts; and every page load sent a visitor's IP address to Google. A
 * school management system holding children's records should not transfer
 * personal data to a third party in order to draw a heading.
 */
`;
fs.writeFileSync(CSS, header + localCss.trim() + '\n');

const total = [...seen.values()].reduce((n, f) => n + fs.statSync(path.join(OUT, f)).size, 0);
console.log(`assets/fonts/  ${seen.size} files · ${(total / 1024).toFixed(0)} KB`);
console.log(`assets/css/fonts.css written`);
